name: CTF
main: org.ctf.eu.Main
version: 1.0
api-version: 1.16
commands:
  testcmd:
    description: testcmd
    usage: /<command>
    permission: <plugin name>.basic
    permission-message:

  togglebreaking:
    description: Toggle block breaking
    usage: /<command>
    permission: <plugin name>.basic
    permission-message:

  addcash:
    description: adds cash to bal
    usage: /<command>
    permission: <plugin name>.basic
    permission-message:

  bal:
    description: shows balance
    usage: /<command>

  upgrades:
    description: opens upgrades gui
    usage: /<command>

  jointeam:
    description: opens upgrades gui
    usage: /<command>